# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # add ---
    - name: dotnet format
      run: |
        dotnet format --verbosity diag --report report.json
        cat report.json
    - name: ls
      run: ls -la AspNetCoreSignalR_React.Server
    # --------
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # add ---
    - name: ls
      run: ls -la AspNetCoreSignalR_React.Server
    - name: 'Package Project Dotnet'
      run: |
        dotnet pack --configuration Release --output ./pack
    # --------
