# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # Walkthrough notes:
    # 1. run as default - show that it works (trigger, runs-on, job/step)
    # 2. a. add  --configuration Release to build script - show that you can change parameters and get build artifacts
    #    b. add upload artifact
    # 3. Add dotnet format abd print out report - show that you can run tests/other scripts
    # 4. a. add dotnet pack & push - Show that you can publish
    #    b. add permissions section
    
    # add ---
    - name: dotnet format
      run: |
        dotnet format --verbosity diag --report report.json
        cat report.json
    # --------
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build  --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # add ---
    - name: 'Package Project Dotnet'
      run: |
        dotnet pack --configuration Release --output ./pack

    - name: upload package
      run: |
        echo "Authenticate Nuget"
        dotnet nuget add source --username "jcantosz-test-org" --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jcantosz-test-org/index.json"
        echo "Push package"
        dotnet nuget push "pack/AspNetCoreSignalR_React.Server.1.0.0.nupkg" --source "github" --skip-duplicate
        
    # --------
    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: AspNetCoreSignalR_React.Server/bin
